insert into cures values('SUCRALAFATE','DUODENAL ULCER');
insert into cures values('SUCRALAFATE','GASTRIC ULCER');
insert into cures values('DICYCLOMINE','BILIARY DISORDER');
insert into cures values('DICYCLOMINE','RENAL COLIC');
insert into cures values('DICYCLOMINE','PEPTIC ULCER');
insert into cures values('DICYCLOMINE','IRRITABLE BOWEL SYNDROME');
insert into cures values('DICYCLOMINE','DIARRHOEA');
insert into cures values('PANCREATIN','PANCREATITIS');
insert into cures values('PANCREATIN','CYSTIC FIBROSIS');
insert into cures values('AMYLASE','OEDEMA');
insert into cures values('AMYLASE','PANCREATITIS');
insert into cures values('AMYLASE','CYSTIC FIBROSIS');
insert into cures values('DOXAZOSIN','HYPERTENSION');
insert into cures values('TERAZOSIN','HYPERTENSION');
insert into cures values('PRAZOSIN','HYPERTENSION');
insert into cures values('CARVEDILOL','ANGINA PECTORIS');
insert into cures values('CARVEDILOL','HYPERTENSION');
insert into cures values('PINDOLOL','HYPERTENSION');
insert into cures values('PINDOLOL','ANGINA PECTORIS');
insert into cures values('PINDOLOL','GLAUCOMA');
insert into cures values('RAMPIRIL','HYPERTENSION');
insert into cures values('RAMPIRIL','HEART FAILURE');
insert into cures values('VERAPAMIL','ISCHAEMIA CORONARY');
insert into cures values('VERAPAMIL','HYPERTENSION');
insert into cures values('RUTIN','EPISTAXIS');
insert into cures values('DIOSMIN','HAEMORRHOIDS');
insert into cures values('DIOSMIN','HAEMORRHAGE');
insert into cures values('WARFARIN','RHEUMATIC DISORDER');
insert into cures values('WARFARIN','PULMONARY EMBOLISM');
insert into cures values('ASPIRIN','PULMONARY EMBOLISM');
insert into cures values('ASPIRIN','MYOCARDIAL GRAVIS');
insert into cures values('UROKINASE','THROMBOSIS');
insert into cures values('UROKINASE','PULMONARY EMBOLISM');
insert into cures values('DIPYRIDAMOLE','THROMBOSIS');
insert into cures values('XIPAMIDE','OEDEMA');
insert into cures values('XIPAMIDE','HYPERTENSION');
insert into cures values('XIPAMIDE','DIABETES INSIPIDUS');
insert into cures values('XIPAMIDE','RENAL FAILURE');
insert into cures values('INDAPAMIDE','HYPERTENSION');
insert into cures values('DISOPYRAMIDE','CARDIAC ARRHYTHMIAS');
insert into cures values('DISOPYRAMIDE','WOLFF-PARKINSON-WHITE SYNDROME');
insert into cures values('DOXEPIN','PSYCHOMOTOR SEIZURES');
insert into cures values('DOXEPIN','DEPRESSIVE STATE');
insert into cures values('DOXEPIN','URTICARIA');
insert into cures values('OLANZAPINE','DEPRESSIVE STATE');
insert into cures values('OLANZAPINE','SCHIZOPHRENIA');
insert into cures values('PIMOZIDE','DEPRESSIVE STATE');
insert into cures values('PIMOZIDE','SCHIZOPHRENIA');
insert into cures values('PRIMIDONE','GRAND MAL EPILEPSY');
insert into cures values('PRIMIDONE','APNOEA');
insert into cures values('PRIMIDONE','TREMOR');
insert into cures values('CARBAMAZEPINE','EPILEPSY');
insert into cures values('CARBAMAZEPINE','NEURALGIA');
insert into cures values('ZOPICLONE','INSOMNIA');
insert into cures values('ZOPICLONE','NOCTURIA');
insert into cures values('TRICLOFOS','INSOMNIA');
insert into cures values('TRICLOFOS','CONVULSIONS');
insert into cures values('OXAZEPAM','ANXIETY STATES');
insert into cures values('OXAZEPAM','STRESS');
insert into cures values('OXAZEPAM','INSOMNIA');
insert into cures values('SUMATRIPTAN','VERTIGO');
insert into cures values('SUMATRIPTAN','PERIPHERAL VASCULAR DISORDER');
insert into cures values('SUMATRIPTAN','MIGRANE');
insert into cures values('PIRIBEDIL','TINNITUS');
insert into cures values('ACARBOSE','HYPOGLYCAEMIA');
insert into cures values('ACARBOSE','DUMPING SYNDROME');
insert into cures values('ACARBOSE','HYPERGLYCAEMIA');
insert into cures values('GLICLAZIDE','HYPERGLYCAEMIA');
insert into cures values('NYSTATIN','CANDIDIASIS VAGINAL');
insert into cures values('HAMYCIN','CANDIDIASIS VAGINAL');
insert into cures values('HAMYCIN','VAGINAL INFECTION');
insert into cures values('HAMYCIN','VAGINAL TRICHOMONIASIS');
insert into cures values('FLAVOXATE','NOCTURIA');
insert into cures values('FLAVOXATE','CYSTITIS');
insert into cures values('FLAVOXATE','URETHRITIS');
insert into cures values('DINOPROSTONE','CERVICITIS');
insert into cures values('OFLOXACIN','RESPIRATORY DEPRESSION');
insert into cures values('OFLOXACIN','URINARY TRACT INFECTION');
insert into cures values('OFLOXACIN','GONORRHOEA');
insert into cures values('AMPICILLIN','GONORRHOEA');
insert into cures values('AMPICILLIN','GASTROENTERITIS');
insert into cures values('AMPICILLIN','BACTERAEMIA');
insert into cures values('AMPICILLIN','SEPTICAEMIA');
insert into cures values('AMPICILLIN','MENINGITIS');
insert into cures values('AMPICILLIN','SALMONELLOSIS');
insert into cures values('CLOXACILLIN','INFECTIONS BACTERIAL');
insert into cures values('AMOXYCILLIN','ACTINOMYCOSIS');
insert into cures values('AMOXYCILLIN','BILIARY TRACT INFECTION');
insert into cures values('AMOXYCILLIN','ENDOCARDITIS');
insert into cures values('AMOXYCILLIN','GONORRHOEA');
insert into cures values('AMOXYCILLIN','OTITIS MEDIA AND EXTERNA');
insert into cures values('AMOXYCILLIN','FEVER');
insert into cures values('AMOXYCILLIN','MENINGITIS');
insert into cures values('CEFTIZOXIME','GONORRHOEA');
insert into cures values('CEFTIZOXIME','CELLULITIS');
insert into cures values('CEFIXIME','BILIARY TRACT INFECTION');
insert into cures values('CEFIXIME','OTITIS MEDIA AND EXTERNA');
insert into cures values('CEFIXIME','GONORRHOEA');
insert into cures values('SISOMICIN','SEPTICAEMIA');
insert into cures values('SISOMICIN','CONJUNCTIVITIS ALLERGIC');
insert into cures values('SISOMICIN','ALLERGY PROPHYLAXIS');
insert into cures values('SISOMICIN','KERATITIS');
insert into cures values('TETRACYCLINE','INFECTIONS BACTERIAL');
insert into cures values('TETRACYCLINE','RESPIRATORY DEPRESSION');
insert into cures values('TETRACYCLINE','HERPES GENITALIS');
insert into cures values('TETRACYCLINE','SYPHILIS');
insert into cures values('TETRACYCLINE','ACNE');
insert into cures values('TETRACYCLINE','MALARIA');
insert into cures values('TETRACYCLINE','DIARRHOEA');
insert into cures values('CLINDAMYCIN','ENDOCARDITIS');
insert into cures values('CLINDAMYCIN','SEPTICAEMIA');
insert into cures values('ERYTHROMYCIN','COUGH');
insert into cures values('ERYTHROMYCIN','PNEUMONIA');
insert into cures values('ERYTHROMYCIN','ACNE');
insert into cures values('ERYTHROMYCIN','ECZEMA');
insert into cures values('ERYTHROMYCIN','FOLLICULITIS');
insert into cures values('ERYTHROMYCIN','URETHRITIS');
insert into cures values('ACYCLOVIR','HERPES ZOSTER ');
insert into cures values('ACYCLOVIR','CHICKEN-POX');
insert into cures values('AMANTADINE','PARKINSONISM');
insert into cures values('AMANTADINE','EXTRAPYRAMIDAL DISORDER');
insert into cures values('RIBAVIRIN','HEPATITIS AMOEBIC');
insert into cures values('RIBAVIRIN','INFLUENZA');
insert into cures values('RIBAVIRIN','RESPIRATORY DEPRESSION');
insert into cures values('ALBENDAZOLE','RINGWORM');
insert into cures values('ALBENDAZOLE','ROUNDWORM');
insert into cures values('ORNIDAZOLE','AMOEBIASIS');
insert into cures values('ORNIDAZOLE','GIARDIASIS');
insert into cures values('ORNIDAZOLE','URINARY TRACT INFECTION');
insert into cures values('FLUCONAZOL','MENINGITIS');
insert into cures values('FLUCONAZOL','CANDIDIASIS VAGINAL');
insert into cures values('FLUCONAZOL','INFECTIONS FUNGAL');
insert into cures values('HAMYCIN','PULMONARY EMBOLISM');
insert into cures values('HAMYCIN','CANDIDIASIS ORAL');
insert into cures values('NYSTATIN','CANDIDIASIS ORAL');
insert into cures values('NYSTATIN','CANDIDIASIS SKIN');
insert into cures values('NYSTATIN','CONJUNCTIVITIS INFECTIVE');
insert into cures values('SPIRULINA','ANAEMIA');
insert into cures values('SPIRULINA','PANCREATITIS');
insert into cures values('SPIRULINA','HEPATITIS AMOEBIC');
insert into cures values('TIMOLOL','GLAUCOMA');
insert into cures values('GENTAMICIN','INFECTIONS BACTERIAL');
insert into cures values('GENTAMICIN','ALLERGY OPTHALMIC');
insert into cures values('GENTAMICIN','ALLERGY PROPHYLAXIS');
insert into cures values('OFLOXACIN','CONJUNCTIVITIS ALLERGIC');
insert into cures values('OFLOXACIN','CONJUNCTIVITIS INFECTIVE');
insert into cures values('OFLOXACIN','BLEPHARITIS');
insert into cures values('OFLOXACIN','ALLERGY PROPHYLAXIS');
insert into cures values('SOFRAMYCIN','CONJUNCTIVITIS ALLERGIC');
insert into cures values('SOFRAMYCIN','CONJUNCTIVITIS INFECTIVE');
insert into cures values('SOFRAMYCIN','BLEPHARITIS');
insert into cures values('ACETAZOLAMIDE','GLAUCOMA');
insert into cures values('ACETAZOLAMIDE','EPILEPSY');
insert into cures values('ACETAZOLAMIDE','PARALYSIS AGITANS');
insert into cures values('BETAHISTINE','MENIERES DISORDER');
insert into cures values('BETAHISTINE','VERTIGO');
insert into cures values('CETIRIZINE','RHINITIS ALLERGIC');
insert into cures values('CETIRIZINE','URTICARIA');
insert into cures values('LORATADINE','URTICARIA');
insert into cures values('LORATADINE','RHINITIS ALLERGIC');
insert into cures values('CALCIPOTRIOL','PSORIASIS');
insert into cures values('TOLNAFTATE','RINGWORM');
insert into cures values('TOLNAFTATE','ATHELETES FOOT');
insert into cures values('TAMOXIFEN','MASTOIDITIS');
insert into cures values('TAMOXIFEN','STERILITY ANOVULATORY');
insert into cures values('CARBOPLATIN','CARCINOMA MAMMARY');
insert into cures values('PRAVASTATIN','CARDIAC ARRHYTHMIAS');
insert into cures values('PRAVASTATIN','CARDIAC SPHINCTER');
insert into cures values('PRAVASTATIN','HYPERCHOLESTEROLAEMIA');
insert into cures values('PIROXICAM','ANKYLOSING SPONDYLITIS');
insert into cures values('PIROXICAM','ARTHRITIC DISORDERS');
insert into cures values('PIROXICAM','GOUT');
insert into cures values('PIROXICAM','DYSMENORRHOEA');
insert into cures values('NIMESULIDE','INFLAMATORY CONDITIONS GENERAL');
insert into cures values('NIMESULIDE','DYSMENORRHOEA');
insert into cures values('NIMESULIDE','LOW BACKBONE SYNDROME');
insert into cures values('NIMESULIDE','OSTEOARTHRITIS');
insert into cures values('VALETHAMATE','CERVICITIS');
insert into cures values('VALETHAMATE','GASTROINTESTINAL SPASM');
insert into cures values('VALETHAMATE','MUSCLE SPASM');
insert into cures values('BACLOFEN','ARTERIOSCLEROSIS');
insert into cures values('BACLOFEN','PARALYSIS AGITANS');
insert into cures values('NALOXONE','UNKNOWN');
insert into cures values('BUPIVACAINE HCL','UNKNOWN');
insert into cures values('MIDAZOLAM','INSOMNIA');
insert into cures values('KETAMINE','UNKNOWN');
