insert into drug values('HYPOGLYCAEMIC','ACARBOSE','25-50mg max');
insert into drug values('DIURETICS','ACETAZOLAMIDE','250-1000mg per day divided in doses');
insert into drug values('ANTIVIRAL','ACYCLOVIR','200mg 5times a day at 4hr intervals');
insert into drug values('ANTIHELMINTIC','ALBENDAZOLE','400mg single dose; 200mg single dose');
insert into drug values('PARKINSONISM','AMANTADINE','200mg in single or in 2 doses');
insert into drug values('ANTIBACTERIAL','AMOXYCILLIN','250-500mg max');
insert into drug values('ANTIBACTERIAL','AMPICILLIN','1-2gm daily divided in doses every 4-6hrs');
insert into drug values('ENZYME','AMYLASE','as per specific requirements');
insert into drug values('ANTIHYPERTENSIVE','BISOPROLOL','20mg max');
insert into drug values('ANTIEPILEPTIC','CARBAMAZEPINE','max 1600mg per day');
insert into drug values('ANTICOAGULANT','DIPYRIDAMOLE','300-600mg per day divided in 4 doses');
insert into drug values('ANTIPSYCHOTIC','OLANZAPINE','5-10mg per day for several days');
insert into drug values('NSAID','PIROXICAM','10-30mg');
insert into drug values('HYPOLIPIDAEMIC','PRAVASTATIN','10-40mg once a day');
insert into drug values('THROMBOLYTIC','ASPIRIN','as per specific requirements');
insert into drug values('MYDRIATIC','ATROPINE','1-2 drops in each eye');
insert into drug values('MUSCLE RELAXANT','BACLOFEN','15mg max; 1-2mg per day divided in doses');
insert into drug values('ANTIVERTIGO','BETAHISTINE','8-16mg after meals');
insert into drug values('ANASTEHTIC','BUPIVACAINE HCL','max 150mg in 4hr');
insert into drug values('ANTIPSORIATC','CALCIPOTRIOL','as per specific requirements');
insert into drug values('ANTINEOPLASTIC','CARBOPLATIN','360mg in a single dose every 4 weeks');
insert into drug values('ANTIHYPERTENSIVE','CARVEDILOL','25mg per day');
insert into drug values('ANTIBACTERIAL','CEFIXIME','200-400mg in 2 doses for a week or two');
insert into drug values('URINARY TRACT ANTIMICROBIAL','CEFTIZOXIME','1-3gm 8-12hrs');
insert into drug values('ANTIALLERGIC','CETIRIZINE','5-10mg');
insert into drug values('ANTIBACTERIAL','CLINDAMYCIN','150-300mg max');
insert into drug values('ANTIBACTERIAL','CLOXACILLIN','250-500mg 6hourly');
insert into drug values('GUT RELAXANT','DICYCLOMINE','10-20mg every 4-6hrs');
insert into drug values('ACT ON UTERU','DINOPROSTONE','max 1.5mg hourly');
insert into drug values('COAGULANT','DIOSMIN','300-450mg every 6hrs');
insert into drug values('ANTIARRHYTHMIC','DISOPYRAMIDE','100-170mg orally every 6hrs');
insert into drug values('ANTIHYPERTENSIVE','DOXAZOSIN','1-16mg per day');
insert into drug values('ANTIDEPRESSANT','DOXEPIN','75-100mg per day in 3 doses');
insert into drug values('ANTBACTERIAL','ERYTHROMYCIN','250mg max; 30-50mg per day in 4 doses');
insert into drug values('URINARY ANTISPASMODIC','FLAVOXATE','200mg');
insert into drug values('ANTIFUNGAL','FLUCONAZOL','500mg per day for a week or two');
insert into drug values('OCULAR ANTIINFECTIVE','GENTAMICIN','1-2 drops only');
insert into drug values('HYPOGLYCAEMIC','GLICLAZIDE','40-80mg per day in 2 doses');
insert into drug values('VAGINAL & URETHRAL','HAMYCIN','apply with sterile cotton 2-3 times a day');
insert into drug values('ANTIHYPERTENSIVE','INDAPAMIDE','2.5mg per day');
insert into drug values('ANAESTHETIC','KETAMINE','as per specific requirements');
insert into drug values('ANTIALLERGIC','LORATADINE','5-10mg daily');
insert into drug values('ANAESTHETIC','MIDAZOLAM','as per specific requirements');
insert into drug values('ANTIDOTAL','NALOXONE','0.4-2mg at 2-3min 10mg max');
insert into drug values('NSAID','NIMESULIDE','100mg; 50mg per day divided in doses');
insert into drug values('VAGINAL & URETHRAL','NYSTATIN','2-4million units oral daily');
insert into drug values('ANTIBACTIRIAL','OFLOXACIN','200-400mg daily 5-7days');
insert into drug values('ANTIPROTOZOAL','ORNIDAZOLE','500mg twice a day for 5 days');
insert into drug values('SEDATIVE','OXAZEPAM','15-30mg 2-3 times a day');
insert into drug values('ENZYME','PANCREATIN','6000 units of amylase ; 560000 units of lipase');
insert into drug values('ANTIPSYCHOTIC','PIMOZIDE','3-4mg per day on average');
insert into drug values('ANTIANGINAL','PINDOLOL','Max 40mg per day');
insert into drug values('CEREBRAL STIMULANT','PIRIBEDIL','1 tablet, twice a day');
insert into drug values('ANTIHYPERTENSIVE','PRAZOSIN','6-15mg per day');
insert into drug values('ANTIEPILEPTIC','PRIMIDONE','as per specific requirements');
insert into drug values('ANTIHYPERTENSIVE','RAMPIRIL','1.25mg increasing to 2.5-5mg ; max 10mg');
insert into drug values('ANTIVIRAL','RIBAVIRIN','200mg 3-4times a day; 10mg per day');
insert into drug values('PHLEBOTONIC','RUTIN','as per specific requirements');
insert into drug values('ANTIBACTERIAL','SISOMICIN','3mg in 3 doses');
insert into drug values('OCULAR ANTIINFECTIVE','SOFRAMYCIN','1-2drops 3-4 times a day');
insert into drug values('ANTIOXIDANT','SPIRULINA','as per specific requirements');
insert into drug values('ANTIULCERANT','SUCRALAFATE','1gm for 4weeks');
insert into drug values('MIGRAINE','SUMATRIPTAN','as per specific requirements');
insert into drug values('ANTINEOPLASTIC','TAMOXIFEN','20-40mg per day');
insert into drug values('ANTIHYPERTENSIVE','TERAZOSIN','Max 20mg per day');
insert into drug values('ANTIBACTERIAL','TETRACYCLINE','2gm divided in doses; 20-40mg divided in doses');
insert into drug values('MIOTIC','TIMOLOL','1 drop of 0.25-0.5% sol');
insert into drug values('ANTIFUNGAL','TOLNAFTATE','apply twice a day and rub gently');
insert into drug values('HYPNOTIC','TRICLOFOS','as per specific requirements');
insert into drug values('THROMBOLYTIC','UROKINASE','treatment(consult physician)');
insert into drug values('MUSCLE RELAXANT','VALETHAMATE','8mg 1ml injection');
insert into drug values('ANTIHYPERTENSIVE','VERAPAMIL','max: 480mg per day');
insert into drug values('ANTICOAGULANT','WARFARIN','2-15mg');
insert into drug values('DIURETIC','XIPAMIDE','40mg per day');
insert into drug values('HYPNOTIC','ZOPICLONE','max 15mg');
