insert into medicine values('ACARBOSE','TABLET','GLUCOBAY','BAYER',10,68.50);
insert into medicine values('ACETAZOLAMIDE','TABLET','DIAMOX','WYETH LEDERLE',10,17.22);
insert into medicine values('ACETAZOLAMIDE','TABLET','SYNOMAX','SYNTHO PHARMA',10,6.90);
insert into medicine values('ACYCLOVIR','TABLET','ACIVIR','CIPLA',10,130.00);
insert into medicine values('ACYCLOVIR','TABLET','CYCLOVIR','CADILA HC',10,57.50);
insert into medicine values('ACYCLOVIR','TABLET','HERPEX','TORRENT',10,65.90);
insert into medicine values('ALBENDAZOLE','TABLET','ANTHEL','LINCOL',10,9.90);
insert into medicine values('ALBENDAZOLE','TABLET','ENVORM','ASHOK PHARMA',20,180.00);
insert into medicine values('ALBENDAZOLE','CAPSULE','GEKARE','GLAXO',1,9.40);
insert into medicine values('ALBENDAZOLE','TABLET','GEKARE','GLAXO',25,235.00);
insert into medicine values('ALBENDAZOLE','SUSPENSION','GEKARE','GLAXO',10,13.50);
insert into medicine values('AMANTADINE','CAPSULE','AMANTREL','PROTEC',10,30.00);
insert into medicine values('AMOXYCILLIN','CAPSULE','ALLMOX','LINCOLN',10,37.90);
insert into medicine values('AMOXYCILLIN','CAPSULE','AMAXYCILLIN','GLAXO ALLENBURYS',10,31.50);
insert into medicine values('AMPICILLIN','CAPSULE','AMPIDIL','DUPHAR',100,196.00);
insert into medicine values('AMPICILLIN','SYRUP','AMPIDIL','DUPHAR',40,70.56);
insert into medicine values('AMPICILLIN','CAPSULE','AMPIPEN','WYETH',10,33.25);
insert into medicine values('AMPICILLIN','SYRUP','AMPIPEN','WYETH',60,315.00);
insert into medicine values('AMPICILLIN','CAPSULE','BIOCILIN','BIOCHEM',10,33.25);
insert into medicine values('AMYLASE','CAPSULE','BESTOZYME','BIOLOGICAL E',10,22.50);
insert into medicine values('BISOPROLOL','TABLET','CONCOR','EMERICK',30,120.00);
insert into medicine values('CARBAMAZEPINE','TABLET','CARBATOL','TORRENT',10,8.98);
insert into medicine values('DIPYRIDAMOLE','TABLET','DYNACARD','USV',10,7.90);
insert into medicine values('DIPYRIDAMOLE','TABLET','THROMBONIL','SUNPHARMA',10,9.60);
insert into medicine values('OLANZAPINE','TABLET','OLANEX','SOLUS',10,14.50);
insert into medicine values('PIROXICAM','TABLET','FELDEX','SUNPHARMA',50,240.00);
insert into medicine values('PIROXICAM','CAPSULE','MOBIDIN','CENTAUR',10,16.50);
insert into medicine values('PIROXICAM','CAPSULE','ROXITEN','MEDICO LABS',10,26.25);
insert into medicine values('PRAVASTATIN','TABLET','PRAVATOR-10','SOLUS',10,71.00);
insert into medicine values('PRAVASTATIN','TABLET','PRAVATOR-20','SOLUS',10,87.00);
insert into medicine values('ASPIRIN','TABLET','ASPENT','SOLUS',14,9.00);
insert into medicine values('ASPIRIN','TABLET','ASPICOT','CONCEPT',14,7.70);
insert into medicine values('ASPIRIN','TABLET','E-PRIN','ELDER',10,6.70);
insert into medicine values('ATROPINE','VIAL','ATROREN-P','WARREN',10,18.80);
insert into medicine values('BACLOFEN','TABLET','LIORESAL','NOVARTIS',30,180.00);
insert into medicine values('BETAHISTINE','TABLET','VERTIN','DUPHAR',10,27.00);
insert into medicine values('CALCIPOTRIOL','OINTMENT','DAIVONEX','CROSLANDS',30,695.00);
insert into medicine values('CARBOPLATIN','VIALINJECTION','CARBOPLAN','OCTAN',150000,852.24);
insert into medicine values('CARVEDILOL','TABLET','CARCA','INTAS',10,26.00);
insert into medicine values('CARVEDILOL','TABLET','CARDIVAS','SUNPHARMA',10,99.00);
insert into medicine values('CEFIXIME','TABLET','CEFSPAN','GALXO',4,120.00);
insert into medicine values('CEFTIZOXIME','VIAL','CEFIZOX','GLAXO',1,242.33);
insert into medicine values('CEFTIZOXIME','VIAL','EPOCELIN','RALLIS',1,250.00);
insert into medicine values('CETIRIZINE','TABLET','CETRIN','DRL',10,27.36);
insert into medicine values('CLINDAMYCIN','CAPSULE','DALACIN-C','MAX PHARMA',4,40.00);
insert into medicine values('CLOXACILLIN','CAPSULE','ALLCLOX','LINCOLN',10,43.60);
insert into medicine values('CLOXACILLIN','CAPSULE','AMPILOX','BIOCHEM',8,39.60);
insert into medicine values('CLOXACILLIN','SYRUP','AMPILOX','BIOCHEM',60,43.25);
insert into medicine values('DICYCLOMINE','TABLET','COLIRID','CADILA HC',10,9.09);
insert into medicine values('DINOPROSTONE','TABLET','PG-TAB','DRL',4,108.00);
insert into medicine values('DINOPROSTONE','TABLET','PRIMITROST','DRL',4,138.14);
insert into medicine values('DINOPROSTONE','SYRINGE','CERVIPRIME-GEL','ASTRA-IDL',1,135.00);
insert into medicine values('DIOSMIN','INJECTION','KAPILIN','GLAXO',10,47.50);
insert into medicine values('DIOSMIN','INJECTION','REVICI','KEE PHARMA',25,75.00);
insert into medicine values('DISOPYRAMIDE','CAPSULE','NORPACE','RPG LIFE SCIENCES',10,60.39);
insert into medicine values('DISOPYRAMIDE','TABLET','REGUBEAT','GLAXO ALLENBURYS',30,107.50);
insert into medicine values('DOXAZOSIN','TABLET','DURACARD','SUNPHARMA',10,80.00);
insert into medicine values('DOXEPIN','CAPSULE','DOXETAR','TORRENT',10,27.90);
insert into medicine values('DOXEPIN','TABLET','SALITOR','SALI HC',10,28.00);
insert into medicine values('DOXEPIN','CAPSULE','EXIPEACE','GLAXO ALLENBURYS',20,16.92);
insert into medicine values('ERYTHROMYCIN','TABLET','E-MYCIN','THEMIS',10,11.84);
insert into medicine values('ERYTHROMYCIN','TABLET','EROATE','LUPIN',10,35.64);
insert into medicine values('ERYTHROMYCIN','TABLET','EROWIN','WINGS',10,25.00);
insert into medicine values('FLUCONAZOL','CAPSULE','FLUCAN','BOMBAY TAB',4,44.25);
insert into medicine values('GENTAMICIN','DPS','GARAMYCIN','FULFORD',3,5.52);
insert into medicine values('GLICLAZIDE','TABLET','DIAMICRON','SERDIA',10,53.59);
insert into medicine values('HAMYCIN','SUSPENSION','HAMYCIN','HAL',10,15.95);
insert into medicine values('INDAPAMIDE','TABLET','LORVAS','TORRENT',10,40.30);
insert into medicine values('KETAMINE','INJECTION','ANEKET','NEON',10,37.80);
insert into medicine values('KETAMINE','INJECTION','KETAMAX','TROIKAA',20,50.90);
insert into medicine values('LORATADINE','TABLET','LORIDIN','CADILA HC',10,25.25);
insert into medicine values('MIDAZOLAM','VIALINJECTION','FULSED','RANBAXY',25,105.00);
insert into medicine values('NALOXONE','SOLUTION','NARCOTAN','TROIKAA',10,250.00);
insert into medicine values('NIMESULIDE','TABLET','DOLOID','LLOYDS',10,20.00);
insert into medicine values('NIMESULIDE','TABLET','N-SIDE','CFL',10,10.00);
insert into medicine values('NIMESULIDE','TABLET','NAM','LINCOLN',20,27.80);
insert into medicine values('NYSTATIN','TABLET','MYCOSTATIN-VAGINAL','SARABHAI',10,25.13);
insert into medicine values('ORNIDAZOLE','TABLET','DAZOLIC','SUNPHARMA',100,452.00);
insert into medicine values('ORNIDAZOLE','INJECTION','DAZOLIC','SUNPHARMA',100,27.50);
insert into medicine values('ORNIDAZOLE','TABLET','GIRO','PANACEA',3,13.50);
insert into medicine values('OXAZEPAM','TABLET','PLACIDOX','LUPIN',10,4.72);
insert into medicine values('OXAZEPAM','TABLET','SEREPAX','WYETH LEDERLE',10,7.20);
insert into medicine values('PANCREATIN','TABLET','ENZYSTAL','TORRENT',10,16.60);
insert into medicine values('PANCREATIN','TABLET','DIZEC','SB',10,22.00);
insert into medicine values('PIMOZIDE','TABLET','MOZEP','INTAS',10,30.00);
insert into medicine values('PIMOZIDE','TABLET','PIMO','MANO PHARMA',10,33.50);
insert into medicine values('PIMOZIDE','TABLET','ORAP','JANSSEN CILAG',10,35.36);
insert into medicine values('PINDOLOL','TABLET','VISKEN','NOVARTIS',10,23.75);
insert into medicine values('PIRIBEDIL','TABLET','TRIVASTAL-LA','SERDIA',10,141.55);
insert into medicine values('PRAZOSIN','TABLET','MINIPRES-XL','PFIZER',15,70.51);
insert into medicine values('PRAZOSIN','TABLET','PRAZOPRESS','SUNPHARMA',10,19.40);
insert into medicine values('PRIMIDONE','TABLET','MYSOLIN','ICI',10,26.95);
insert into medicine values('RAMPIRIL','CAPSULE','CARADACE','HMR',10,26.00);
insert into medicine values('RAMPIRIL','TABLET','RAMACE','ASTRA-IDL',10,25.50);
insert into medicine values('RAMPIRIL','TABLET','CORPRIL','SOLUS',10,25.00);
insert into medicine values('RIBAVIRIN','TABLET','RIBAVIN','LUPIN',4,113.37);
insert into medicine values('RIBAVIRIN','SYRUP','RIBAVIN','LUPIN',30,81.47);
insert into medicine values('RUTIN','TABLET','DROTIN','WALTER BUSHNELL',8,16.00);
insert into medicine values('SISOMICIN','INJECTION','SISOPTIN','TATA',1,9.13);
insert into medicine values('SISOMICIN','DPS','ENSAMYCIN','FULFORD',3,19.00);
insert into medicine values('SOFRAMYCIN','DPS','SOFRAMYCIN','HMR',5,8.36);
insert into medicine values('SOFRAMYCIN','OINTMENT','SOFRAMYCIN','HMR',5,7.20);
insert into medicine values('SPIRULINA','TABLET','RECOLINA','RECON',10,13.00);
insert into medicine values('SPIRULINA','TABLET','ZYRULINA','ZYDUS',30,58.50);
insert into medicine values('SUCRALAFATE','TABLET','SUCRAMAL','MENARINI RAUNAQ',10,25.00);
insert into medicine values('SUCRALAFATE','SUSPENSION','SUCRAMAL','MENARINI RAUNAQ',100,56.00);
insert into medicine values('SUMATRIPTAN','TABLET','SUMINAT','NATCO',1,29.00);
insert into medicine values('SUMATRIPTAN','INJECTION','SUMINAT','NATCO',5,35.35);
insert into medicine values('SUMATRIPTAN','TABLET','MIGRATANE','DABUR',2,110.00);
insert into medicine values('SUMATRIPTAN','TABLET','SUMITREX','SUNPHARMA',1,29.00);
insert into medicine values('TAMOXIFEN','TABLET','CLADITAM','CADILA PH',10,16.39);
insert into medicine values('TAMOXIFEN','TABLET','MAMOFEN','KHANDELWAL',10,29.21);
insert into medicine values('TAMOXIFEN','TABLET','ONCOTAM','ONCOMED',10,20.85);
insert into medicine values('TERAZOSIN','TABLET','TERALFA','TORRENT',10,75.60);
insert into medicine values('TERAZOSIN','TABLET','OLYSTER','CADILA HC',10,82.50);
insert into medicine values('TETRACYCLINE','CAPSULE','IDILIN','IDPL',10,10.95);
insert into medicine values('TETRACYCLINE','CAPSULE','TETRET','LEBEN LAB',12,15.24);
insert into medicine values('TIMOLOL','DPS','IOTIM','FDC',5,14.20);
insert into medicine values('TIMOLOL','DPS','OCOBAR','PCI',5,22.90);
insert into medicine values('TIMOLOL','DPS','OCULAN','BAL PHARMA',5,13.50);
insert into medicine values('TOLNAFTATE','SOLUTION','TINADERM','FULFORD',10,17.00);
insert into medicine values('TOLNAFTATE','OINTMENT','TINADERM','FULFORD',10,16.06);
insert into medicine values('TOLNAFTATE','SOLUTION','TOLSOL','JAGSON PAL',10,14.51);
insert into medicine values('TRICLOFOS','LIQUID','TRICLORYL','GLAXO',60,38.00);
insert into medicine values('UROKINASE','VIALINJECTION','UKIDAN','SERUM INST',500000,4077.90);
insert into medicine values('UROKINASE','VIALINJECTION','UROKINASE','TTK PHARMA',500000,3640.00);
insert into medicine values('VALETHAMATE','TABLET','EPIDOSIN','TTK PHARMA',10,9.53);
insert into medicine values('VALETHAMATE','INJECTION','EPIDOSIN','TTK PHARMA',5,42.90);
insert into medicine values('VALETHAMATE','INJECTION','OSDIL','TROIKAA',5,36.75);
insert into medicine values('VERAPAMIL','INJECTION','CALAPTIN','NICHOLAS PIRAMAL',2,2.21);
insert into medicine values('VERAPAMIL','TABLET','CALAPTIN','NICHOLAS PIRAMAL',10,6.63);
insert into medicine values('VERAPAMIL','TABLET','VASOPTEN','TORRENT',10,8.86);
insert into medicine values('VERAPAMIL','INJECTION','VASOPTEN','TORRENT',2,8.23);
insert into medicine values('VERAPAMIL','TABLET','VERAMIL','THEMIS',10,5.02);
insert into medicine values('WARFARIN','TABLET','UNIWARFARIN','UNICHEM',10,20.05);
insert into medicine values('XIPAMIDE','TABLET','XIPAMIDE','GERMAN REMEDIES',100,315.501);
insert into medicine values('ZOPICLONE','TABLET','ZOPICON','INTAS',10,50.75);
