insert into treats values('SP013','PEPTIC ULCER');
insert into treats values('SP013','ALLERGY OPTHALMIC');
insert into treats values('SP023','OSTEOARTHRITIS');
insert into treats values('SP09','INSOMNIA');
insert into treats values('SP023','INSOMNIA');
insert into treats values('SP026','GRAND MAL EPILEPSY');
insert into treats values('SP020','ROUNDWORM');
insert into treats values('SP016','SALMONELLOSIS');
insert into treats values('SP04','KERATITIS');
insert into treats values('SP028','HAEMORRHOIDS');
insert into treats values('SP018','APNOEA');
insert into treats values('SP01','TREMOR');
insert into treats values('SP023','STRESS');
insert into treats values('SP015','PULMONARY EMBOLISM');
insert into treats values('SP03','ACTINOMYCOSIS');
insert into treats values('SP03','PANCREATITIS');
insert into treats values('SP03','CARDIAC ARRHYTHMIAS');
insert into treats values('SP017','PERIPHERAL VASCULAR DISORDER');
insert into treats values('SP07','STRESS');
insert into treats values('SP030','ANAEMIA');
insert into treats values('SP010','LOW BACKBONE SYNDROME');
insert into treats values('SP023','DIARRHOEA');
insert into treats values('SP011','HERPES ZOSTER');
insert into treats values('SP026','PSORIASIS');
insert into treats values('SP022','OEDEMA');
insert into treats values('SP023','NOCTURIA');
insert into treats values('SP01','DUMPING SYNDROME');
insert into treats values('SP026','HERPES GENITALIS');
insert into treats values('SP029','FEVER');
insert into treats values('SP08','STERILITY ANOVULATORY');
insert into treats values('SP023','VERTIGO');
insert into treats values('SP015','DIARRHOEA');
insert into treats values('SP023','HYPOGLYCAEMIA');
insert into treats values('SP05','CONVULSIONS');
insert into treats values('SP015','FOLLICULITIS');
insert into treats values('SP03','PANCREATITIS');
insert into treats values('SP015','UNKNOWN');
insert into treats values('SP013','CARCINOMA MAMMARY');
insert into treats values('SP010','CYSTIC FIBROSIS');
insert into treats values('SP025','UNKNOWN');
insert into treats values('SP07','LOW BACKBONE SYNDROME');
insert into treats values('SP018','CONVULSIONS');
insert into treats values('SP011','STERILITY ANOVULATORY');
insert into treats values('SP07','HEART FAILURE');
insert into treats values('SP029','OEDEMA');
insert into treats values('SP02','CARCINOMA MAMMARY');
insert into treats values('SP02','EXTRAPYRAMIDAL DISORDER');
insert into treats values('SP030','ACTINOMYCOSIS');
insert into treats values('SP015','ALLERGY PROPHYLAXIS');
insert into treats values('SP016','WOLFF-PARKINSON-WHITE SYNDROME');
insert into treats values('SP07','COUGH');
insert into treats values('SP023','ROUNDWORM');
insert into treats values('SP05','BACTERAEMIA');
insert into treats values('SP01','IRRITABLE BOWEL SYNDROME');
insert into treats values('SP022','AMOEBIASIS');
insert into treats values('SP013','BACTERAEMIA');
insert into treats values('SP01','LOW BACKBONE SYNDROME');
insert into treats values('SP023','RHEUMATIC DISORDER');
insert into treats values('SP015','CHICKEN-POX');
insert into treats values('SP013','INSOMNIA');
insert into treats values('SP015','BLEPHARITIS');
insert into treats values('SP024','CELLULITIS');
insert into treats values('SP010','LOW BACKBONE SYNDROME');
insert into treats values('SP012','ENDOCARDITIS');
insert into treats values('SP028','DYSMENORRHOEA');
insert into treats values('SP016','MASTOIDITIS');
insert into treats values('SP020','KERATITIS');
insert into treats values('SP02','RINGWORM');
insert into treats values('SP013','TINNITUS');
insert into treats values('SP011','PERIPHERAL VASCULAR DISORDER');
insert into treats values('SP06','CANDIDIASIS SKIN');
insert into treats values('SP012','STERILITY ANOVULATORY');
insert into treats values('SP05','ANKYLOSING SPONDYLITIS');
insert into treats values('SP024','LOW BACKBONE SYNDROME');
insert into treats values('SP07','GOUT');
insert into treats values('SP025','MIGRANE');
insert into treats values('SP020','ACNE');
insert into treats values('SP07','ANGINA PECTORIS');
insert into treats values('SP028','CYSTITIS');
insert into treats values('SP05','UNKNOWN');
insert into treats values('SP026','STERILITY ANOVULATORY');
insert into treats values('SP06','TREMOR');
insert into treats values('SP024','PERIPHERAL VASCULAR DISORDER');
insert into treats values('SP02','ISCHAEMIA CORONARY');
insert into treats values('SP014','FOLLICULITIS');
insert into treats values('SP05','ANGINA PECTORIS');
insert into treats values('SP018','MENINGITIS');
insert into treats values('SP019','ARTERIOSCLEROSIS');
insert into treats values('SP029','CANDIDIASIS VAGINAL');
insert into treats values('SP03','ISCHAEMIA CORONARY');
insert into treats values('SP021','ACNE');
insert into treats values('SP010','DUODENAL ULCER');
insert into treats values('SP02','HYPERCHOLESTEROLAEMIA');
insert into treats values('SP020','PEPTIC ULCER');
insert into treats values('SP06','HYPOGLYCAEMIA');
insert into treats values('SP06','PARALYSIS AGITANS');
insert into treats values('SP04','RINGWORM');
insert into treats values('SP030','BILIARY TRACT INFECTION');
insert into treats values('SP01','DIABETES INSIPIDUS');
insert into treats values('SP06','ISCHAEMIA CORONARY');
insert into treats values('SP029','HYPERTENSION');
insert into treats values('SP023','STRESS');
insert into treats values('SP04','DEPRESSIVE STATE');
insert into treats values('SP06','CONJUNCTIVITIS INFECTIVE');
insert into treats values('SP029','NOCTURIA');
insert into treats values('SP012','URTICARIA');
insert into treats values('SP02','GOUT');
insert into treats values('SP015','DYSMENORRHOEA');
insert into treats values('SP012','VERTIGO');
insert into treats values('SP020','GONORRHOEA');
insert into treats values('SP025','INFLAMATORY CONDITIONS GENERAL');
insert into treats values('SP021','ARTERIOSCLEROSIS');
insert into treats values('SP015','EXTRAPYRAMIDAL DISORDER');
insert into treats values('SP028','RENAL COLIC');
insert into treats values('SP01','HYPOGLYCAEMIA');
insert into treats values('SP024','PARKINSONISM');
insert into treats values('SP022','THROMBOSIS');
insert into treats values('SP026','ANXIETY STATES');
insert into treats values('SP025','EXTRAPYRAMIDAL DISORDER');
insert into treats values('SP012','AMOEBIASIS');
insert into treats values('SP030','TREMOR');
insert into treats values('SP028','CONJUNCTIVITIS INFECTIVE');
insert into treats values('SP013','ARTHRITIC DISORDERS');
insert into treats values('SP017','RENAL COLIC');
insert into treats values('SP030','ISCHAEMIA CORONARY');
insert into treats values('SP027','GIARDIASIS');
insert into treats values('SP012','RENAL COLIC');
insert into treats values('SP022','BILIARY DISORDER');
insert into treats values('SP029','GASTROINTESTINAL SPASM');
insert into treats values('SP07','GASTROINTESTINAL SPASM');
insert into treats values('SP020','HERPES GENITALIS');
insert into treats values('SP026','HYPERCHOLESTEROLAEMIA');
insert into treats values('SP013','PERIPHERAL VASCULAR DISORDER');
insert into treats values('SP021','ALLERGY PROPHYLAXIS');
insert into treats values('SP03','PEPTIC ULCER');
insert into treats values('SP08','OEDEMA');
insert into treats values('SP019','null');
insert into treats values('SP010','ECZEMA');
insert into treats values('SP03','BACTERAEMIA');
insert into treats values('SP06','RENAL COLIC');
insert into treats values('SP029','OTITIS MEDIA AND EXTERNA');
insert into treats values('SP014','RENAL FAILURE');
insert into treats values('SP026','WOLFF-PARKINSON-WHITE SYNDROME');
insert into treats values('SP013','GONORRHOEA');
insert into treats values('SP013','ANGINA PECTORIS');
insert into treats values('SP01','NEURALGIA');
insert into treats values('SP014','PARKINSONISM');
insert into treats values('SP09','DYSMENORRHOEA');
insert into treats values('SP026','TREMOR');
insert into treats values('SP012','DUODENAL ULCER');
insert into treats values('SP018','MIGRANE');
insert into treats values('SP03','FEVER');
insert into treats values('SP029','RESPIRATORY DEPRESSION');
insert into treats values('SP09','MYOCARDIAL GRAVIS');
insert into treats values('SP027','TREMOR');
insert into treats values('SP024','PARKINSONISM');
insert into treats values('SP010','COUGH');
insert into treats values('SP014','GRAND MAL EPILEPSY');
insert into treats values('SP025','GLAUCOMA');
insert into treats values('SP029','ISCHAEMIA CORONARY');
insert into treats values('SP08','SALMONELLOSIS');
insert into treats values('SP015','DIABETES INSIPIDUS');
insert into treats values('SP02','DYSMENORRHOEA');
insert into treats values('SP03','HERPES GENITALIS');
insert into treats values('SP06','CARCINOMA MAMMARY');
insert into treats values('SP018','RENAL FAILURE');
insert into treats values('SP013','HYPERCHOLESTEROLAEMIA');
insert into treats values('SP014','KERATITIS');
insert into treats values('SP08','HAEMORRHAGE');
insert into treats values('SP01','INFECTIONS BACTERIAL');
insert into treats values('SP030','ENDOCARDITIS');
insert into treats values('SP027','SALMONELLOSIS');
insert into treats values('SP016','EPILEPSY');
insert into treats values('SP017','SEPTICAEMIA');
insert into treats values('SP021','SYPHILIS');
insert into treats values('SP015','ECZEMA');
insert into treats values('SP016','MIGRANE');
insert into treats values('SP05','MIGRANE');
insert into treats values('SP02','TREMOR');
insert into treats values('SP030','URETHRITIS');
insert into treats values('SP016','URINARY TRACT INFECTION');
insert into treats values('SP09','PERIPHERAL VASCULAR DISORDER');
insert into treats values('SP013','RHEUMATIC DISORDER');
insert into treats values('SP04','SALMONELLOSIS');
insert into treats values('SP011','CONVULSIONS');
insert into treats values('SP013','URINARY TRACT INFECTION');
insert into treats values('SP021','MYOCARDIAL GRAVIS');
insert into treats values('SP026','BILIARY TRACT INFECTION');
insert into treats values('SP02','HERPES GENITALIS');
insert into treats values('SP03','URETHRITIS');
insert into treats values('SP05','OTITIS MEDIA AND EXTERNA');
insert into treats values('SP014','APNOEA');
insert into treats values('SP04','ACTINOMYCOSIS');
insert into treats values('SP09','DUMPING SYNDROME');
insert into treats values('SP03','PERIPHERAL VASCULAR DISORDER');
insert into treats values('SP09','CYSTIC FIBROSIS');
insert into treats values('SP023','GASTROENTERITIS');
insert into treats values('SP029','SYPHILIS');
insert into treats values('SP023','PULMONARY EMBOLISM');
insert into treats values('SP024','MUSCLE SPASM');
insert into treats values('SP029','MALARIA');
insert into treats values('SP030','PANCREATITIS');
insert into treats values('SP024','GASTRIC ULCER');
insert into treats values('SP028','OTITIS MEDIA AND EXTERNA');
insert into treats values('SP017','DUODENAL ULCER');
insert into treats values('SP07','CONVULSIONS');
insert into treats values('SP028','CARDIAC SPHINCTER');
insert into treats values('SP02','ALLERGY PROPHYLAXIS');
insert into treats values('SP015','MIGRANE');
insert into treats values('SP029','NOCTURIA');
insert into treats values('SP05','INSOMNIA');
insert into treats values('SP027','WOLFF-PARKINSON-WHITE SYNDROME');
insert into treats values('SP024','CARDIAC ARRHYTHMIAS');
insert into treats values('SP027','GLAUCOMA');
insert into treats values('SP030','GRAND MAL EPILEPSY');
insert into treats values('SP011','HAEMORRHAGE');
insert into treats values('SP09','URINARY TRACT INFECTION');
insert into treats values('SP014','CARDIAC SPHINCTER');
insert into treats values('SP026','DYSMENORRHOEA');
insert into treats values('SP08','BILIARY DISORDER');
insert into treats values('SP028','CANDIDIASIS SKIN');
insert into treats values('SP016','CANDIDIASIS ORAL');
insert into treats values('SP026','GLAUCOMA');
insert into treats values('SP029','MENINGITIS');
insert into treats values('SP05','DIABETES INSIPIDUS');
insert into treats values('SP024','RHEUMATIC DISORDER');
insert into treats values('SP04','ARTHRITIC DISORDERS');
insert into treats values('SP020','MALARIA');
insert into treats values('SP022','URETHRITIS');
insert into treats values('SP025','BILIARY DISORDER');
insert into treats values('SP01','INFLUENZA');
insert into treats values('SP04','RESPIRATORY DEPRESSION');
insert into treats values('SP01','PNEUMONIA');
insert into treats values('SP09','DUMPING SYNDROME');
insert into treats values('SP02','HYPERGLYCAEMIA');
insert into treats values('SP019','ARTERIOSCLEROSIS');
insert into treats values('SP027','SYPHILIS');
insert into treats values('SP020','CONJUNCTIVITIS ALLERGIC');
insert into treats values('SP030','MENINGITIS');
insert into treats values('SP016','CONJUNCTIVITIS ALLERGIC');
insert into treats values('SP029','PSYCHOMOTOR SEIZURES');
insert into treats values('SP016','MALARIA');
insert into treats values('SP019','RENAL COLIC');
insert into treats values('SP02','TINNITUS');
insert into treats values('SP015','HEART FAILURE');
insert into treats values('SP024','EXTRAPYRAMIDAL DISORDER');
insert into treats values('SP016','STRESS');
insert into treats values('SP022','HYPOGLYCAEMIA');
insert into treats values('SP015','CERVICITIS');
insert into treats values('SP026','WOLFF-PARKINSON-WHITE SYNDROME');
insert into treats values('SP029','OTITIS MEDIA AND EXTERNA');
insert into treats values('SP024','ACTINOMYCOSIS');
insert into treats values('SP019','CONJUNCTIVITIS ALLERGIC');
insert into treats values('SP09','COUGH');
insert into treats values('SP08','GRAND MAL EPILEPSY');
insert into treats values('SP026','HAEMORRHAGE');
insert into treats values('SP07','GRAND MAL EPILEPSY');
insert into treats values('SP012','PERIPHERAL VASCULAR DISORDER');
insert into treats values('SP01','OEDEMA');
insert into treats values('SP025','HEPATITIS AMOEBIC');
insert into treats values('SP024','MASTOIDITIS');
insert into treats values('SP08','AMOEBIASIS');
insert into treats values('SP016','FOLLICULITIS');
insert into treats values('SP019','MALARIA');
insert into treats values('SP027','TINNITUS');
insert into treats values('SP07','HEART FAILURE');
insert into treats values('SP024','COUGH');
insert into treats values('SP024','RENAL FAILURE');
insert into treats values('SP024','MIGRANE');
insert into treats values('SP015','MENIERES DISORDER');
insert into treats values('SP04','ARTERIOSCLEROSIS');
insert into treats values('SP012','null');
insert into treats values('SP012','ANXIETY STATES');
insert into treats values('SP029','DEPRESSIVE STATE');
insert into treats values('SP025','HYPERTENSION');
insert into treats values('SP07','RENAL FAILURE');
insert into treats values('SP02','HEPATITIS AMOEBIC');
insert into treats values('SP014','MASTOIDITIS');
insert into treats values('SP014','RESPIRATORY DEPRESSION');
insert into treats values('SP021','PSORIASIS');
insert into treats values('SP09','HERPES GENITALIS');
insert into treats values('SP030','VAGINAL TRICHOMONIASIS');
insert into treats values('SP030','INFECTIONS FUNGAL');
insert into treats values('SP029','ALLERGY PROPHYLAXIS');
insert into treats values('SP022','GASTRIC ULCER');
insert into treats values('SP02','HAEMORRHAGE');
insert into treats values('SP019','GLAUCOMA');
insert into treats values('SP022','STERILITY ANOVULATORY');
insert into treats values('SP020','HYPERCHOLESTEROLAEMIA');
insert into treats values('SP09','CANDIDIASIS VAGINAL');
insert into treats values('SP05','RHINITIS ALLERGIC');
insert into treats values('SP09','IRRITABLE BOWEL SYNDROME');
insert into treats values('SP027','ANXIETY STATES');
insert into treats values('SP029','ENDOCARDITIS');
insert into treats values('SP030','MENINGITIS');
insert into treats values('SP07','BACTERAEMIA');
insert into treats values('SP05','ANKYLOSING SPONDYLITIS');
insert into treats values('SP018','ATHELETES FOOT');
insert into treats values('SP018','GIARDIASIS');
insert into treats values('SP011','CHICKEN-POX');
